---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
  tags: vars

- name: ensure available_java_packages is defined for os
  fail:
    msg: >
      Available java packages is not defined!
      Probably the os you are trying to install java on is not supported by this role
      right now. Please ensure that os distribution is defined in vars/ folder.
  when: available_java_packages is not defined

- name: ensure selected java_package is available for os
  fail:
    msg: >
      Java package is not available!
      Probably the os you are trying to install java on is not support {{ java_package }}
      package right now. Please ensure that the package you want to install is available for
      this os distribution.
  when: java_package not in available_java_packages

- name: install java
  package:
    name: "{{ available_java_packages[java_package] }}"
    state: present
  tags: packages