---
- name: include os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family|lower }}/{{ ansible_distribution|lower }}/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family|lower }}/{{ ansible_distribution|lower }}/{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}/{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}/{{ ansible_os_family|lower }}.yml"
  tags: [ include ]

- name: ensure available_packages is defined for os
  fail:
    msg: >
        Available java packages is not defined!
        Probably the os you are trying to install java on is not supported by this role
        right now. Please ensure that os distribution is defined in vars/ folder.
  when: available_packages is not defined

- name: ensure selected java package is available for os
  fail:
    msg: >
        Java package is not available!
        Probably the os you are trying to install java on is not support {{ java_env }}
        {{ java_ver }} package right now. Please ensure that the package you want to install
        is available for this os distribution.
  when: "java_env ~ java_ver not in available_packages"

- name: include os specific tasks for installment
  include_tasks: "{{ item }}"
  with_first_found:
    - "package/{{ ansible_os_family|lower }}/{{ ansible_distribution|lower }}.yml"
    - "package/{{ ansible_os_family|lower }}.yml"
  register: package_result
  tags: [ include ]

- name: configure java environment
  include: configure.yml