---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos6-jre-6
    groups: [ jre6 ]
    image: finnetdevlab/fnn-ansible-managed:centos6
    pre_build_image: True

  - name: centos6-jdk-6
    groups: [ jdk6 ]
    image: finnetdevlab/fnn-ansible-managed:centos6
    pre_build_image: True

  - name: centos6-jre-7
    groups: [ jre7 ]
    image: finnetdevlab/fnn-ansible-managed:centos6
    pre_build_image: True

  - name: centos6-jdk-7
    groups: [ jdk7 ]
    image: finnetdevlab/fnn-ansible-managed:centos6
    pre_build_image: True

  - name: centos6-jre-8
    groups: [ jre8 ]
    image: finnetdevlab/fnn-ansible-managed:centos6
    pre_build_image: True

  - name: centos6-jdk-8
    groups: [ jdk8 ]
    image: finnetdevlab/fnn-ansible-managed:centos6
    pre_build_image: True

  - name: centos7-jre-7
    groups: [ jre7 ]
    image: finnetdevlab/fnn-ansible-managed:centos7
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: centos7-jdk-7
    groups: [ jdk7 ]
    image: finnetdevlab/fnn-ansible-managed:centos7
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: centos7-jre-8
    groups: [ jre8 ]
    image: finnetdevlab/fnn-ansible-managed:centos7
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: centos7-jdk-8
    groups: [ jdk8 ]
    image: finnetdevlab/fnn-ansible-managed:centos7
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: centos7-jre-11
    groups: [ jre11 ]
    image: finnetdevlab/fnn-ansible-managed:centos7
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: centos7-jdk-11
    groups: [ jdk11 ]
    image: finnetdevlab/fnn-ansible-managed:centos7
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: centos8-jre-8
    groups: [ jre8 ]
    image: finnetdevlab/fnn-ansible-managed:centos8
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: centos8-jdk-8
    groups: [ jdk8 ]
    image: finnetdevlab/fnn-ansible-managed:centos8
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: centos8-jre-11
    groups: [ jre11 ]
    image: finnetdevlab/fnn-ansible-managed:centos8
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: centos8-jdk-11
    groups: [ jdk11 ]
    image: finnetdevlab/fnn-ansible-managed:centos8
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True
provisioner:
  name: ansible
verifier: 
  name: testinfra
  directory: ../../tests
