---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian8-jre-7
    groups: [ jre7 ]
    image: finnetdevlab/fnn-ansible-managed:debian8
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: debian8-jdk-7
    groups: [ jdk7 ]
    image: finnetdevlab/fnn-ansible-managed:debian8
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: debian9-jre-8
    groups: [ jre8 ]
    image: finnetdevlab/fnn-ansible-managed:debian9
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: debian9-jdk-8
    groups: [ jdk8 ]
    image: finnetdevlab/fnn-ansible-managed:debian9
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: debian10-jre-11
    groups: [ jre11 ]
    image: finnetdevlab/fnn-ansible-managed:debian10
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True

  - name: debian10-jdk-11
    groups: [ jdk11 ]
    image: finnetdevlab/fnn-ansible-managed:debian10
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: True
provisioner:
  name: ansible
verifier: 
  name: testinfra
  directory: ../../tests
